/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArtworkRatingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createArtwork"
      | "getArtworkCount"
      | "getArtworkInfo"
      | "getEncryptedCount"
      | "getEncryptedTotalScore"
      | "hasRated"
      | "protocolId"
      | "submitRating"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArtworkCreated"
      | "AverageScoreDecrypted"
      | "RatingSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createArtwork",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getArtworkCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getArtworkInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createArtwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtworkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArtworkInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRated", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
}

export namespace ArtworkCreatedEvent {
  export type InputTuple = [
    artworkId: BigNumberish,
    artist: AddressLike,
    title: string
  ];
  export type OutputTuple = [artworkId: bigint, artist: string, title: string];
  export interface OutputObject {
    artworkId: bigint;
    artist: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AverageScoreDecryptedEvent {
  export type InputTuple = [
    artworkId: BigNumberish,
    averageScore: BigNumberish
  ];
  export type OutputTuple = [artworkId: bigint, averageScore: bigint];
  export interface OutputObject {
    artworkId: bigint;
    averageScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [artworkId: BigNumberish, judge: AddressLike];
  export type OutputTuple = [artworkId: bigint, judge: string];
  export interface OutputObject {
    artworkId: bigint;
    judge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtworkRating extends BaseContract {
  connect(runner?: ContractRunner | null): ArtworkRating;
  waitForDeployment(): Promise<this>;

  interface: ArtworkRatingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createArtwork: TypedContractMethod<[title: string], [bigint], "nonpayable">;

  getArtworkCount: TypedContractMethod<[], [bigint], "view">;

  getArtworkInfo: TypedContractMethod<
    [artworkId: BigNumberish],
    [
      [string, string, bigint] & {
        title: string;
        artist: string;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  getEncryptedCount: TypedContractMethod<
    [artworkId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedTotalScore: TypedContractMethod<
    [artworkId: BigNumberish],
    [string],
    "view"
  >;

  hasRated: TypedContractMethod<
    [artworkId: BigNumberish, judge: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitRating: TypedContractMethod<
    [artworkId: BigNumberish, encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createArtwork"
  ): TypedContractMethod<[title: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getArtworkCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getArtworkInfo"
  ): TypedContractMethod<
    [artworkId: BigNumberish],
    [
      [string, string, bigint] & {
        title: string;
        artist: string;
        ratingCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedCount"
  ): TypedContractMethod<[artworkId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalScore"
  ): TypedContractMethod<[artworkId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasRated"
  ): TypedContractMethod<
    [artworkId: BigNumberish, judge: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [artworkId: BigNumberish, encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArtworkCreated"
  ): TypedContractEvent<
    ArtworkCreatedEvent.InputTuple,
    ArtworkCreatedEvent.OutputTuple,
    ArtworkCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AverageScoreDecrypted"
  ): TypedContractEvent<
    AverageScoreDecryptedEvent.InputTuple,
    AverageScoreDecryptedEvent.OutputTuple,
    AverageScoreDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;

  filters: {
    "ArtworkCreated(uint256,address,string)": TypedContractEvent<
      ArtworkCreatedEvent.InputTuple,
      ArtworkCreatedEvent.OutputTuple,
      ArtworkCreatedEvent.OutputObject
    >;
    ArtworkCreated: TypedContractEvent<
      ArtworkCreatedEvent.InputTuple,
      ArtworkCreatedEvent.OutputTuple,
      ArtworkCreatedEvent.OutputObject
    >;

    "AverageScoreDecrypted(uint256,uint256)": TypedContractEvent<
      AverageScoreDecryptedEvent.InputTuple,
      AverageScoreDecryptedEvent.OutputTuple,
      AverageScoreDecryptedEvent.OutputObject
    >;
    AverageScoreDecrypted: TypedContractEvent<
      AverageScoreDecryptedEvent.InputTuple,
      AverageScoreDecryptedEvent.OutputTuple,
      AverageScoreDecryptedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
  };
}
